name = "anonymous-world"
owners = ["suzy", "lana"]
users = [ {
  id = "suzy"
  name = "suzy"
  email = "suzy@example.com"
  roles = ["employee", "manager"]
}, {
  id = "lana"
  name = "lana"
  email = "lana@example.com"
  roles = ["employee", "manager"]
}]