services:
  cassandra:
    image: cassandra:3.11
    labels:
      component: event-store
    network_mode: host
    expose:
      - 9042
    container_name: cassandra
    healthcheck:
      test: [ "CMD", "cqlsh", "--execute", "show version;quit" ]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-for-cassandra:
    image: postgres:12.1-alpine
    network_mode: host
    expose:
      - 9432
    hostname: postgres
    container_name: postgres-for-cassandra
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-query
    command: postgres --port=9432

  empty-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: host
    expose:
      - 1433
    hostname: empty-sql-server
    container_name: empty-sql-server
    environment:
      SA_PASSWORD: Abc_123456
      ACCEPT_EULA: Y
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &

      until /opt/mssql-tools18/bin/sqlcmd -l 1 -C -No -S 0.0.0.0 -U sa -P 'Abc_123456' -Q 'SELECT 1'; do
        echo '>>>>>>>>>> SQL Server is unavailable - sleeping <<<<<<<<<<';
        sleep 5;
      done;
      echo '>>>>>>>>>> SQL Server is ready - executing init script <<<<<<<<<<';
      /opt/mssql-tools18/bin/sqlcmd -l 5 -C -No -S 0.0.0.0 -U sa -P 'Abc_123456' -d master -i /tmp/mssql-init.sql;
      
      sleep infinity;"
    volumes:
    - /home/circleci/cafienne-engine/.circleci/docker-config/mssql-init.sql:/tmp/mssql-init.sql

  postgres-empty-event-db:
    image: postgres:12.1-alpine
    network_mode: host
    expose:
      - 5431
    hostname: cafienne-event-db
    container_name: postgres-empty-event-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-eventstore
    command: postgres --port=5431

  postgres-empty-query-db:
    image: postgres:12.1-alpine
    network_mode: host
    expose:
      - 5430
    hostname: postgres-empty-query-db
    container_name: postgres-empty-query-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-query
    command: postgres --port=5430

  postgres-with-events:
    image: batav/circle-ci:postgres-event-data
    network_mode: host
    expose:
      - 6431
    hostname: postgres-with-events
    container_name: postgres-with-events
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-eventstore
      PGDATA: event-data
    command: postgres --port=6431

  postgres-query-db-for-events:
    image: postgres:12.1-alpine
    network_mode: host
    expose:
      - 6430
    hostname: postgres
    container_name: postgres-query-db-for-events
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-query
    command: postgres --port=6430

  postgres-for-cluster:
    image: postgres:16
    network_mode: host
    command: postgres -c 'max_connections=1000' --port=6432
    container_name: postgres-for-cluster
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
#      - "POSTGRES_HOST_AUTH_METHOD=scram-sha-256"
#      - "POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256"
    ports:
      - "6432:6432"
    expose:
      - 6432
    hostname: postgres-for-cluster
    volumes:
      - "/home/circleci/cafienne-engine/.circleci/src/cluster-conf/postgres-init:/docker-entrypoint-initdb.d"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres --port 6432" ]
      interval: 5s
      timeout: 5s
      retries: 5
