services:
  sql-server-with-events:
    image: batav/circle-ci:sqlserver-event-data
    labels:
      component: cafienne-sql-server
    network_mode: host
    expose:
      - 1433
    hostname: sql-server
    container_name: sql-server-with-events
    environment:
      SA_PASSWORD: Abc_123456
      ACCEPT_EULA: Y
      QUERY_DB: cafienneQuery
      EVENT_DB: cafienneEventstore
