services:
  cafienne:
    image: casefabric/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    hostname: cafienne
    container_name: cafienne
    restart: on-failure
    environment:
      EVENT_DB_PROFILE: ${EVENT_DB_PROFILE:-slick.jdbc.SQLServerProfile$$}
      EVENT_DB_DRIVER: ${EVENT_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      EVENT_DB_USER: ${EVENT_DB_USER:-SA}
      EVENT_DB_PASSWORD: ${EVENT_DB_PASSWORD:-Abc_123456}
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneEventstore;sendStringParametersAsUnicode=false;encrypt=false;}
      QUERY_DB_PROFILE: ${QUERY_DB_PROFILE:-slick.jdbc.SQLServerProfile$$}
      QUERY_DB_DRIVER: ${QUERY_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      QUERY_DB_USER: ${QUERY_DB_USER:-SA}
      QUERY_DB_PASSWORD: ${QUERY_DB_PASSWORD:-Abc_123456}
      QUERY_DB_URL: ${QUERY_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneQuery;encrypt=false;}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/casefabric-engine/.circleci/run/cafienne/journal:/opt/casefabric/journal
      - /home/circleci/casefabric-engine/.circleci/run/cafienne/archive:/opt/casefabric/archive
      - /home/circleci/casefabric-engine/.circleci/target/definitions:/opt/casefabric/definitions
      - /home/circleci/casefabric-engine/.circleci/src/jdbc-conf:/opt/casefabric/conf
      - /home/circleci/casefabric-engine/.circleci/src/bootstrap:/opt/casefabric/bootstrap
