services:
  cafienne:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    hostname: cafienne
    container_name: cafienne
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/journal:/opt/cafienne/journal
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/archive:/opt/cafienne/archive
      - /home/circleci/cafienne-engine/.circleci/target/definitions:/opt/cafienne/definitions
      - /home/circleci/cafienne-engine/.circleci/src/anonymous-conf:/opt/cafienne/conf
      - /home/circleci/cafienne-engine/.circleci/src/bootstrap:/opt/cafienne/bootstrap
