services:
  casefabric:
    image: casefabric/engine:latest
    labels:
      component: casefabric-engine
    network_mode: host
    expose:
      - 2027
    hostname: casefabric
    container_name: casefabric
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/casefabric-engine/.circleci/run/casefabric/journal:/opt/casefabric/journal
      - /home/circleci/casefabric-engine/.circleci/run/casefabric/archive:/opt/casefabric/archive
      - /home/circleci/casefabric-engine/.circleci/target/definitions:/opt/casefabric/definitions
      - /home/circleci/casefabric-engine/.circleci/src/anonymous-conf:/opt/casefabric/conf
      - /home/circleci/casefabric-engine/.circleci/src/bootstrap:/opt/casefabric/bootstrap
