package org.cafienne.persistence.eventdb.schema.hsqldb

import org.cafienne.infrastructure.Cafienne
import org.cafienne.persistence.eventdb.schema.ClassicEventDBSchemaScript

class V1_1_17__CreateAkkaSchema extends ClassicEventDBSchemaScript {
  val version = "1.1.17"

  val description = "CreateAkkaSchemaDurableState"

  val scriptName = "org.cafienne.persistence.schema.V1_1_17__CreateAkkaSchemaDurableState"

  override def getChecksum: Integer = 1702145591

  override def sql: String = {
    s"""
       |CREATE TABLE IF NOT EXISTS "PUBLIC"."${Cafienne.config.persistence.tablePrefix}durable_state" (
       |    global_offset BIGINT GENERATED BY DEFAULT AS IDENTITY,
       |    persistence_id VARCHAR(255) NOT NULL,
       |    revision BIGINT NOT NULL,
       |    state_payload BLOB NOT NULL,
       |    state_serial_id INTEGER NOT NULL,
       |    state_serial_manifest VARCHAR(255),
       |    tag VARCHAR(255),
       |    state_timestamp BIGINT NOT NULL,
       |    PRIMARY KEY(persistence_id)
       |    );""".stripMargin
  }
 }
