/*
 * Copyright 2014 - 2019 Cafienne B.V.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package org.cafienne.timerservice;

import com.fasterxml.jackson.core.JsonGenerator;
import org.cafienne.akka.actor.command.BootstrapCommand;
import org.cafienne.akka.actor.event.ModelEvent;
import org.cafienne.akka.actor.identity.TenantUser;
import org.cafienne.akka.actor.serialization.AkkaSerializable;
import org.cafienne.akka.actor.serialization.Manifest;
import org.cafienne.cmmn.instance.casefile.ValueMap;
import org.cafienne.timerservice.TimerService;
import org.cafienne.timerservice.TimerStorage;
import org.cafienne.timerservice.akka.command.SetTimer;

import java.io.IOException;
import java.time.Instant;

/**
 * TimerServiceEvents are generated by the {@link TimerService}.
 */
@Manifest
public class TimerJob implements AkkaSerializable {
    public final String caseInstanceId;
    public final Instant moment;
    public final String timerId;
    public final TenantUser user;

    public TenantUser getUser() {
        return user;
    }

    protected enum Fields {
        timerId , caseInstanceId, moment, user
    }

    public TimerJob(SetTimer command) {
        this.timerId = command.timerId;
        this.caseInstanceId = command.caseInstanceId;
        this.moment = command.moment;
        this.user = command.getUser();
    }

    public TimerJob(ValueMap json) {
        this.caseInstanceId = readField(json, Fields.caseInstanceId);
        this.moment = readInstant(json, Fields.moment);
        this.timerId = readField(json, Fields.timerId);
        this.user = TenantUser.from(json.with(Fields.user));
    }

    @Override
    public void write(JsonGenerator generator) throws IOException {
        writeField(generator, Fields.timerId, timerId);
        writeField(generator, Fields.caseInstanceId, caseInstanceId);
        writeField(generator, Fields.moment, moment);
        generator.writeFieldName(ModelEvent.Fields.user.toString());
        user.write(generator);
    }
}
